# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='chosen_answer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='text',
            field=models.CharField(max_length=3000),
        ),
    ]
