# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-10 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20161209_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='chosen_answer',
        ),
    ]
